services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: dpg-d0ai8dgdl3ps73eb4bt0-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: proyectoalojamientos
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: DaHSbOg8HARvkKrhZd9K2SGEsghjWbdq
